CREATE TABLE R (A INT, B INT, C INT, D INT, E INT, F INT);
CREATE TABLE F (x VARCHAR(10), y VARCHAR(10), violation BOOLEAN, motivation VARCHAR(200));
CREATE TABLE R1 ();
CREATE TABLE R2 ();
CREATE TABLE F1 ();
CREATE TABLE F2 ();